apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbddevopsdemo01
  labels:
    app: cbddevopsdemo01
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718377392947
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbddevopsdemo01
  template:
    metadata:
      labels:
        app: cbddevopsdemo01
    spec:
      containers:
        - name: cbddevopsdemo01
          image: cbsacr98.azurecr.io/cbspetclinicdemo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
