apiVersion: apps/v1
kind: Deployment
metadata:
  name: CBSDemoDevOps2
  labels:
    app: CBSDemoDevOps2
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718375748000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CBSDemoDevOps2
  template:
    metadata:
      labels:
        app: CBSDemoDevOps2
    spec:
      containers:
        - name: CBSDemoDevOps2
          image: cbsacr98.azurecr.io/petclinicacrcbsdemo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
