apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbddevopsdemo02
  labels:
    app: cbddevopsdemo02
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718729719162
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbddevopsdemo02
  template:
    metadata:
      labels:
        app: cbddevopsdemo02
    spec:
      containers:
        - name: cbddevopsdemo02
          image: cbsacr98.azurecr.io/cbspetclinicdemo2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
