apiVersion: v1
kind: Service
metadata:
  name: cbddevopsdemo01
  namespace: namespace-workflow-1718378497416
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: cbddevopsdemo01
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080