apiVersion: v1
kind: Service
metadata:
  name: cbddevopsdemo02
  namespace: namespace-workflow-1718644181980
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: cbddevopsdemo02
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080